"""Initial migration

Revision ID: 2df4c024bfde
Revises: d4e38d6183f3
Create Date: 2023-12-26 20:00:18.086464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df4c024bfde'
down_revision: Union[str, None] = 'd4e38d6183f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('category', sa.Enum('work', 'household', 'education', 'personal', 'health', 'shopping', 'family', 'travel', 'projects', 'urgent', name='categories'), nullable=True))
    op.add_column('users', sa.Column('firt_name', sa.String(), nullable=True))
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'firt_name')
    op.drop_column('tasks', 'category')
    # ### end Alembic commands ###
