"""Initial migration

Revision ID: db1f53fce50e
Revises: 
Create Date: 2023-12-26 14:41:05.074643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1f53fce50e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('category', sa.Enum('work', 'household', 'education', 'personal', 'health', 'shopping', 'family', 'travel', 'projects', 'urgent', name='categories'), nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), nullable=True))
    op.drop_column('tasks', 'category')
    # ### end Alembic commands ###
